# ============================================================================
# JDRK 水质监控平台 · Windows 后端服务管理
#
# 后端 jdrk-monitor.exe 是控制台程序，没有实现 Windows 服务控制管理器(SCM)接口，
# 用 New-Service 注册会报 1053（服务未及时响应启动请求），所以这里改为注册
# 「开机计划任务」来托管：
#   · 触发器：开机（SYSTEM 权限，无需用户登录）
#   · 失败自动重启：间隔 1 分钟，最多 5 次
#   · 无执行时长上限；已在运行时忽略重复启动
# 停止时优先调用 POST /api/shutdown 优雅退出（释放串口），失败再终止任务。
#
# 用法：
#   .\jdrk-service.ps1 -Action Install          # 注册并启动
#   .\jdrk-service.ps1 -Action Status           # 查看状态（任务 + 健康接口 + 进程）
#   .\jdrk-service.ps1 -Action Stop             # 优雅停止
#   .\jdrk-service.ps1 -Action Uninstall        # 停止并注销任务
#   .\jdrk-service.ps1 -Action Firewall         # 添加防火墙入站规则
#   .\jdrk-service.ps1 -Action RemoveFirewall   # 删除防火墙规则
# ============================================================================
[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)]
    [ValidateSet('Install', 'Uninstall', 'Start', 'Stop', 'Restart', 'Status', 'Firewall', 'RemoveFirewall')]
    [string]$Action,

    [string]$AppDir = '',
    [string]$Config = '',
    [string]$LogDir = '',
    [string]$DataDir = '',
    [int]$Port = 8790,
    [string]$TaskName = 'JDRK-Monitor-Backend',
    [switch]$NoStart
)

$ErrorActionPreference = 'Stop'

# ---------------------------------------------------------------- 默认路径
if (-not $AppDir)  { $AppDir = Split-Path -Parent $PSScriptRoot }
if (-not $Config)  { $Config = Join-Path $env:ProgramData 'JDRK\config.toml' }
if (-not $LogDir)  { $LogDir = Join-Path $env:ProgramData 'JDRK\logs' }
if (-not $DataDir) { $DataDir = Join-Path $env:ProgramData 'JDRK\data' }
if ($AppDir)  { $AppDir = (Resolve-Path -LiteralPath $AppDir).Path }
$backendExe = Join-Path $AppDir 'backend\jdrk-monitor.exe'
$cmdFile = Join-Path $LogDir 'run-backend.cmd'
$logFile = Join-Path $LogDir 'backend.log'
$fwRuleName = 'JDRK Monitor (TCP ' + $Port + ')'

function Write-Info  { param([string]$m) Write-Host ('[jdrk] ' + $m) }
function Write-Warn2 { param([string]$m) Write-Warning ('[jdrk] ' + $m) }

function Test-Health {
    param([int]$TimeoutSec = 3)
    try {
        return Invoke-RestMethod -Uri ('http://127.0.0.1:' + $Port + '/api/health') -TimeoutSec $TimeoutSec
    } catch {
        return $null
    }
}

function Wait-Health {
    param([int]$TimeoutSec = 25)
    $deadline = (Get-Date).AddSeconds($TimeoutSec)
    while ((Get-Date) -lt $deadline) {
        $h = Test-Health
        if ($h) { return $h }
        Start-Sleep -Milliseconds 700
    }
    return $null
}

# ---------------------------------------------------------------- 任务动作
function New-RunCmdFile {
    # 用 .cmd 包一层：统一日志重定向 + 固定工作目录（避免计划任务参数里嵌套引号）
    if (-not (Test-Path -LiteralPath $LogDir)) {
        New-Item -ItemType Directory -Force -Path $LogDir | Out-Null
    }
    $lines = @(
        '@echo off',
        'rem generated by jdrk-service.ps1 - re-run "-Action Install" to regenerate',
        ('cd /d "' + (Join-Path $AppDir 'backend') + '"'),
        ('"' + $backendExe + '" --config "' + $Config + '" >> "' + $logFile + '" 2>&1')
    )
    # .cmd 由 cmd.exe 以 OEM 代码页解析，用 OEM 写入才能兼容含中文的安装路径
    $oem = [System.Text.Encoding]::GetEncoding([System.Globalization.CultureInfo]::CurrentCulture.TextInfo.OEMCodePage)
    [System.IO.File]::WriteAllText($cmdFile, [string]::Join([Environment]::NewLine, $lines), $oem)
    Write-Info ('生成启动脚本：' + $cmdFile)
}

function Register-JdrkTask {
    New-RunCmdFile
    $taskAction = New-ScheduledTaskAction -Execute 'cmd.exe' -Argument ('/c "' + $cmdFile + '"') -WorkingDirectory $AppDir
    $trigger = New-ScheduledTaskTrigger -AtStartup
    $settings = New-ScheduledTaskSettingsSet -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries -StartWhenAvailable -RestartCount 5 -RestartInterval (New-TimeSpan -Minutes 1) -ExecutionTimeLimit ([TimeSpan]::Zero) -MultipleInstances IgnoreNew
    $principal = New-ScheduledTaskPrincipal -UserId 'SYSTEM' -LogonType ServiceAccount -RunLevel Highest
    Register-ScheduledTask -TaskName $TaskName -Action $taskAction -Trigger $trigger -Settings $settings -Principal $principal -Force -Description 'JDRK 水质监控平台后端（Modbus 采集 + REST/WebSocket），由安装程序注册。' | Out-Null
    Write-Info ('已注册计划任务：' + $TaskName + '（开机启动，SYSTEM 权限）')
}

function Stop-JdrkTask {
    param([int]$TimeoutSec = 15)
    $wasRunning = $false
    try {
        $info = Get-ScheduledTask -TaskName $TaskName -ErrorAction Stop
        $wasRunning = ($info.State -eq 'Running')
    } catch {
        Write-Warn2 ('未找到计划任务 ' + $TaskName)
    }
    $procs = @(Get-Process -Name 'jdrk-monitor' -ErrorAction SilentlyContinue)

    if ($wasRunning -or $procs.Count -gt 0) {
        # 1) 优雅停机：后端收到请求后先关闭串口再退出
        try {
            Invoke-RestMethod -Method Post -Uri ('http://127.0.0.1:' + $Port + '/api/shutdown') -TimeoutSec 3 | Out-Null
            Write-Info '已请求优雅停机（POST /api/shutdown）'
        } catch {
            Write-Warn2 '优雅停机接口不可达，改用任务/进程终止'
        }
        # 2) 等待进程退出
        $deadline = (Get-Date).AddSeconds($TimeoutSec)
        while ((Get-Date) -lt $deadline) {
            if (@(Get-Process -Name 'jdrk-monitor' -ErrorAction SilentlyContinue).Count -eq 0) { break }
            Start-Sleep -Milliseconds 500
        }
    }
    # 3) 兜底：结束任务与残留进程
    if ($wasRunning) {
        try { Stop-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue } catch { }
    }
    $left = @(Get-Process -Name 'jdrk-monitor' -ErrorAction SilentlyContinue)
    if ($left.Count -gt 0) {
        Write-Warn2 ('仍有 ' + $left.Count + ' 个 jdrk-monitor 进程，强制执行停止')
        $left | Stop-Process -Force -ErrorAction SilentlyContinue
        Start-Sleep -Milliseconds 500
    }
    Write-Info '后端已停止'
}

function Add-FirewallRule {
    if (Get-NetFirewallRule -DisplayName $fwRuleName -ErrorAction SilentlyContinue) {
        Write-Info ('防火墙规则已存在：' + $fwRuleName)
        return
    }
    try {
        New-NetFirewallRule -DisplayName $fwRuleName -Direction Inbound -Action Allow -Protocol TCP -LocalPort $Port -Profile Any | Out-Null
        Write-Info ('已添加防火墙入站规则：' + $fwRuleName)
    } catch {
        Write-Warn2 ('New-NetFirewallRule 失败，改用 netsh：' + $_.Exception.Message)
        netsh advfirewall firewall add rule name="$fwRuleName" dir=in action=allow protocol=TCP localport=$Port | Out-Null
        Write-Info ('已通过 netsh 添加入站规则：' + $fwRuleName)
    }
}

function Remove-FirewallRule {
    if (Get-NetFirewallRule -DisplayName $fwRuleName -ErrorAction SilentlyContinue) {
        try {
            Remove-NetFirewallRule -DisplayName $fwRuleName -ErrorAction SilentlyContinue
        } catch {
            netsh advfirewall firewall delete rule name="$fwRuleName" | Out-Null
        }
        Write-Info ('已删除防火墙规则：' + $fwRuleName)
    } else {
        Write-Info '防火墙规则不存在，无需删除'
    }
}

function Show-Status {
    $task = $null
    try { $task = Get-ScheduledTask -TaskName $TaskName -ErrorAction Stop } catch { }
    if ($task) {
        $info = Get-ScheduledTaskInfo -TaskName $TaskName
        Write-Info ('计划任务 ' + $TaskName + '：状态 ' + $task.State + '  上次运行 ' + $info.LastRunTime + '  上次结果 ' + $info.LastTaskResult)
    } else {
        Write-Warn2 ('计划任务 ' + $TaskName + ' 未注册')
    }
    $procs = @(Get-Process -Name 'jdrk-monitor' -ErrorAction SilentlyContinue)
    Write-Info ('后端进程数：' + $procs.Count)
    $health = Test-Health
    if ($health) {
        Write-Info ('REST 健康检查：正常  http://127.0.0.1:' + $Port + '/api/health')
        Write-Info ('  ' + ($health | ConvertTo-Json -Compress))
    } else {
        Write-Warn2 ('REST 健康检查失败（http://127.0.0.1:' + $Port + '/api/health 不可达）')
    }
}

# ---------------------------------------------------------------- 主流程
switch ($Action) {
    'Install' {
        if (-not (Test-Path -LiteralPath $backendExe)) {
            throw ('后端可执行文件不存在：' + $backendExe)
        }
        foreach ($d in @($DataDir, $LogDir)) {
            if (-not (Test-Path -LiteralPath $d)) { New-Item -ItemType Directory -Force -Path $d | Out-Null }
        }
        if (-not (Test-Path -LiteralPath $Config)) {
            Write-Warn2 ('配置文件不存在：' + $Config + '（后端将使用内置默认值启动）')
        }
        Register-JdrkTask
        if (-not $NoStart) {
            Start-ScheduledTask -TaskName $TaskName
            Write-Info '已启动计划任务，等待后端就绪…'
            $h = Wait-Health -TimeoutSec 25
            if ($h) {
                Write-Info '后端已就绪，REST/WebSocket 服务可访问。'
            } else {
                Write-Warn2 ('后端在 25 秒内未通过健康检查，请查看日志：' + $logFile)
            }
        }
    }
    'Uninstall' {
        Stop-JdrkTask
        Remove-FirewallRule
        if (Get-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue) {
            Unregister-ScheduledTask -TaskName $TaskName -Confirm:$false
            Write-Info ('已注销计划任务 ' + $TaskName)
        }
        if (Test-Path -LiteralPath $cmdFile) { Remove-Item -LiteralPath $cmdFile -Force -ErrorAction SilentlyContinue }
    }
    'Start'   { Start-ScheduledTask -TaskName $TaskName; Write-Info '已启动计划任务' }
    'Stop'    { Stop-JdrkTask }
    'Restart' { Stop-JdrkTask; Start-Sleep -Seconds 1; Start-ScheduledTask -TaskName $TaskName; Write-Info '已重启计划任务' }
    'Status'  { Show-Status }
    'Firewall'       { Add-FirewallRule }
    'RemoveFirewall' { Remove-FirewallRule }
}

exit 0
